project:
  type: website

website:
  page-navigation: true
  title: "TAXA Project"
  site-url: ""
  repo-url: "https://github.com/Miller-Library/taxa_webV2"
  repo-actions: [edit, source, issue]
  favicon: millerlogo.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    title: "TAXA Project"
    background: "#D9E3E4"
    logo: "images/millerlogo.png"
    favicon: millerlogo.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://library.stanford.edu/hopkins
        text: "Hopkins Marine Station"
      - icon: github
        href: https://github.com/Miller-Library
        text: "Harold A. Miller Library"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/plan.qmd
        text: Project Plan
      - href: content/experiments.ipynb
        text: Experiments
      - href: content/Option1.ipynb
        text: Option 1 Notebook
      - href: content/Option2final.ipynb
        text: Option 2 Notebook
      - href: content/Global_Biodiversity_Information_Facility_(GBIF)_API.ipynb
        text: GBIF API Test
      - href: content/ComparingResults-Options1&2.ipynb
        text: Results Table - Options 1 & 2
      - href: content/Text_Difference_Checker.ipynb
        text: difflib Transkribus Output Text Checker
        contents:
        - href: "Text Checker/Outputs/bv172tc9618_jpg"
          text: bv172tc9618 Comparison

      - href: content/PyTesseract_OCR.ipynb
        text: PyTesseract_OCR - Improving OCR'd Papers

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
